apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-app-deployment
  labels:
    app: hw3-app
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: hw3-app
  template:
    metadata:
      labels:
        app: hw3-app
    spec:
      containers:
      - name: hw3-app
        image: saadatkhan/hw3-app
        ports:
        - containerPort: 8080  # Port on which the application listens
        