apiVersion: v1
kind: Service
metadata:
  name: hw3-app-service
spec:
  selector:
    app: hw3-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007  # Specify a port in the allowed range (default: 30000-32767)
  type: NodePort  # This exposes the service on each Node’s IP at a static port
